### ISSUE TITLE
No defined license

### ISSUE THREAD

**Issue by xavfernandez** [Shir0kamii/csvalidate#6]
Hello,

I heard about this project and came to take a look but I could not find its license.

Have a nice day !

**Comment by Shir0kamii** [comment]
I've been very, very late on this, but this is fixed!

**Comment by xavfernandez** [comment]
I don't remember how I came across this project anymore 😅 but thanks anyway 👍.
You might even put the license in your setup.py like this: https://github.com/pypa/pip/blob/master/setup.py#L43.

**Comment by Shir0kamii** [comment]
Good idea, I just did that. :+1:
